version: "3"

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.50.0.0/16
        
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ../envs/mosquitto/config:/mosquitto/config
      - ../envs/mosquitto/data:/mosquitto/data
      - ../envs/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    networks:
      mynetwork:
        ipv4_address: "172.50.0.4"
  
  influxdb2:
    image: influxdb:2.6
    container_name: influxdb2
    volumes:
      - ../envs/influxdb/data:/var/lib/influxdb2
      - ../envs/influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=secret-password
      - DOCKER_INFLUXDB_INIT_ORG=my-init-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-init-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret-token
    networks:
      mynetwork:
        ipv4_address: "172.50.0.5"

